Little code style rework. Also change Log.Info to Log.Debug
CedModV2/SCPSLAudioApi pull request #3
Opened 2023-05-16 11:05 UTC by FakeMan2332

2023-06-17 18:51 UTC, SrLicht commented
Why are you moving the library to be only compatible with Exiled ?

2023-07-10 02:27 UTC, xNexus-ACS commented
> Why are you moving the library to be only compatible with Exiled ?

bcs NwAPI sucks

2023-07-10 02:28 UTC, SrLicht commented
> > Why are you moving the library to be only compatible with Exiled ?
> 
> bcs NwAPI sucks

And that is a valid reason?

2023-07-10 11:00 UTC, xNexus-ACS commented
> > > Why are you moving the library to be only compatible with Exiled ?
> 
> > 
> 
> > bcs NwAPI sucks
> 
> 
> 
> And that is a valid reason?

Yes :trollface:

2023-07-10 11:05 UTC, SrLicht commented
Que pelotudo de tu parte.

2023-09-24 10:16 UTC, ced777ric requested changes
There is no reason to add exiled as dependency, the goal of this api is to be framework independant.

2025-10-25 07:04 UTC, closed without merging